# Generated by Django 3.1.6 on 2021-02-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210216_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='drink_type',
            new_name='type',
        ),
    ]
