# Generated by Django 3.1.6 on 2021-02-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210220_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
    ]
