# Generated by Django 3.1.6 on 2021-02-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(max_length=900, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
