# Generated by Django 3.1.6 on 2021-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(max_length=900, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
