# Generated by Django 3.1.6 on 2021-03-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_card'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
