# Generated by Django 3.1.6 on 2021-03-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210306_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='card',
        ),
    ]
